apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: polyglot-lab-cluster-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: polyglot-lab-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: polyglot-vuln-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polyglot-lab-cluster-admin
